---
kind: pipeline
type: docker
name: default

steps:
  - name: build-push
    image: docker:20.10
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - docker build -t daburch/homelab-docs:0.0.1 .
      - docker push daburch/homelab-docs:0.0.1