kind: pipeline
type: docker
name: default

steps:
  - name: build-push
    image: plugins/docker
    settings:
      repo: daburch/homelab-docs
      tags: 0.0.1
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASSWORD