site_name: Homelab Documentation
site_description: Simple documentation about my homelab setup.
repo_url: https://github.com/daburch/homelab-docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.code.copy
    - navigation.expand
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Overview: index.md
  - Proxmox: proxmox.md
  - OPNSense: opnsense.md
  - Kubernetes: kubernetes.md
  - PiHole: pihole.md
  - Caddy: caddy.md
  - TrueNAS: truenas.md
  - Terraform: terraform.md
  - Vaultwarden: vaultwarden.md
  - Servarr: servarr.md
  - Homepage: homepage.md
  - Tekton: tekton.md
  - Docs: docs.md