apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-docs
  namespace: homelab-docs
  labels:
    "app.kubernetes.io/name": "homelab-docs"
spec:
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": homelab-docs
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": homelab-docs
    spec:
      containers:
        - name: homelab-docs
          image: REPLACE_IMAGE
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault